### ISSUE TITLE
M3/A8 reboot on robot

### ISSUE THREAD

**Issue by vandaele** [iot-lab/iot-lab#121]
problem rebooting GW with software on/off from turtlebot2
no problem by base rebooting
-> test relay solution

**Comment by pissard** [comment]
We try "on table"  the Panasonic AQY 212 GS component. We do not success to operate it. We must investigate futher.

**Comment by pissard** [comment]
Guillaume proposes a solution controling the node alimentation with a PC USB port using 
http://www.yoctopuce.com/EN/products/usb-actuators/yocto-relay

**Comment by pissard** [comment]
With the auto-alimentation relay solution (PVG612PBF), the problem is the same :-(
We will test solution with external alim and a relay to try to better understand. We will also contact HikoB.

**Comment by schrein** [comment]
I've managed to make this relay working (USB-RLY02 - 2 relay outputs at 16A) :+1: 

buy on : 
http://www.gotronic.fr/art-interface-usb-2-relais-usb-rly02-12171.htm

technical doc :+1: 
http://www.robot-electronics.co.uk/htm/usb_rly02tech.htm

Python script on github : 
https://github.com/superalex/Python-RLY02/blob/master/rly02.py

When the relay is ON (red light on), the node is OFF :
sudo python ./rly02.py -r 1 -a on

When the relay is OFF (red light off), the node is ON : 
sudo python ./rly02.py -r 1 -a off

By default relay state is off, and the node should be on with the robot.

**Comment by pissard** [comment]
good job Guillaume ! Forget my previous comment. on the voltage range. I have made some measures on the board. If the board on/off is short (less than few seconds) or if the impedance is not infinite during the off (output of an alimentation or a mems relay) the local alimentations are not correct: 2.98 v instead of 3.3 v and 3.07 v instead of 5.0 v for the gateway...
So i used a solution with a mechanical relay controled by the 12v5A of the kobuki to on/off the 5v. This solution is cheaper (5 euros) adding a cable without touching the actual cable.

![img_20150306_145649](https://cloud.githubusercontent.com/assets/3606134/6526477/9c5377ea-c412-11e4-9931-89450f389c30.jpg)

**Comment by pissard** [comment]
Jeff will realize a new prototype that can be easily duplicated. After the protype test, he will write a fab paper for subcontractors.

**Comment by schrein** [comment]
Finally we used and deployed the USB-RLY02 solution.
