### ISSUE TITLE
Cannot find Serial Port IDs for nodes

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#239]
Hello, I am trying to write serial port data to a 'csv' file.
Assuming, I have 2 nodes: m3-100, m3-101, their port ids would be dev/tty0 and dev/tty1 respectively or something else. I also intend to customize data before dumping to csv.

I checked the log files, they do not dump the run-time data.

I received the following error when I am trying to execute the python script. 
is this a permission issue or something else??

![image](https://user-images.githubusercontent.com/25517038/45662899-688c0600-bac9-11e8-9372-73cd24acd3ba.png)

![image](https://user-images.githubusercontent.com/25517038/45663319-6c208c80-bacb-11e8-9d0b-08ffdfee6d97.png)

And **sudo doesn't work for me. My password always fails.**

**Setup:** 2 M3 nodes, Grenoble site

Alternatively, is there a better way to do this.

Please help.

**Comment by rienafairefr** [comment]
when on the SSH frontend, /dev/tty* don't redirect to any nodes. They are not physically connected.

As you've seen in other tutorials, the serial data is redirected on the TCP port 20000 for each node (you can use `nc m3-100 20000` to get to the serial link of node m3-100)

You could manually open multiple links to the nodes through e.g. socat and shell pipes, but we've built a serial aggregator to simplify this. Tutorial is [here](https://www.iot-lab.info/tutorials/nodes-serial-link-aggregation)

`serial_aggregator > data.log` will dump the data. You can also write some Python code to extend the aggregator tools (code is open source [here](https://github.com/iot-lab/aggregation-tools) so that you fetch only the data you want and save that to a CSV, if that's what you want. But usually what we do is let the serial aggregator run, piped to a log file, `serial_aggregator > logs.log` then parse the log file to extract only what we need.

**Comment by npcode15** [comment]
@rienafairefr 
Thanks.
