### ISSUE TITLE
Average Packet/Data Rate

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#244]
Hello, 

Device - M3

Is there a way to identify standard/average data communication rate over the radio between 2 nodes (say Grenoble site, consecutive nodes).

If yes, I would like to know the data rate from a one device. I already checked the data sheet. I could not anything regarding this.

Thank you.

**Comment by schrein** [comment]
Hi @npcode15 , M3 and A8 node implement IEEE802.15.4 with at86rf231 radio chip. See complete data sheet here http://ww1.microchip.com/downloads/en/devicedoc/doc8111.pdf . See section 11.3.1
High Data Rate Modes, it should be typically 250 kb/s at max. 

With FIT IoT-LAB, you could try to use the sniffer functionality in order to capture all packet at radio range of your node. You have to filter by yourself the traffic with Wireshark in order to evaluate the tx/rx traffic from a given node, see as a starting point https://www.iot-lab.info/tutorials/monitoring-sniffer-m3/
