### ISSUE TITLE
MQTT-SN with public IPv6 network and A8-M3 nodes with 2 mqttsn clients

### ISSUE THREAD

**Issue by nainiayoub** [iot-lab/iot-lab#264]
I would like to use not only one emcute_mqttsn client but two clients, and subscribe both clients to the same topic, but when I tried to publish the message into the topic, only the last client connected to the broker who shows that the message was succefuly received by showing it. How so?

**Comment by aabadie** [comment]
Sorry for replying late.

The issue you have is because the 2 RIOT mqtt applications are registered on the broker with the same IDs.
You edit this value in the `main.c`, [here](https://github.com/RIOT-OS/RIOT/blob/master/examples/emcute_mqttsn/main.c#L32). Ensure the 2 instances are using 2 differents IDs. After, you'll be able to publish/subscribe messages from/between both instances and/or a mosquitto_client on the frontend.

Using this change, I was able to connect 2 instances of RIOT and publish/subscribe messages. I'll close this issue for now, feel to reopen if you still have the issue.
